/**
 * Renderers for the `nanocoder completion <shell>` scripts. Every word list,
 * flag, description, and value set below is derived from `spec.ts` — nothing
 * is hardcoded here, so adding a flag to the spec is all it takes to expose
 * it in bash, zsh, and fish completions at once.
 */

import {
	COMPLETION_FLAGS,
	COMPLETION_SUBCOMMANDS,
	type CompletionFlag,
} from './spec';

function longFlagNames(): string[] {
	return COMPLETION_FLAGS.map(f => `--${f.name}`);
}

/** Escape a description for use inside a single-quoted zsh string. zsh
 * treats backslash as literal inside single quotes, so the only
 * metacharacter is `'`, handled by the splice idiom. */
function zshEscape(text: string): string {
	return text.replace(/'/g, `'\\''`);
}

/** Escape a description for use inside a single-quoted fish string. Unlike
 * zsh, fish treats backslash as an escape even inside single quotes, so
 * backslashes must be doubled before quotes are escaped. */
function fishEscape(text: string): string {
	return text.replace(/\\/g, `\\\\`).replace(/'/g, `\\'`);
}

function flagsWithValues(): Array<{
	name: string;
	values: readonly string[];
}> {
	return COMPLETION_FLAGS.flatMap(f =>
		f.values ? [{name: f.name, values: f.values}] : [],
	);
}

function subcommandsWithChildren(): Array<{
	name: string;
	children: readonly string[];
}> {
	return COMPLETION_SUBCOMMANDS.flatMap(s =>
		s.children ? [{name: s.name, children: s.children}] : [],
	);
}

function bashValueCases(): string {
	return flagsWithValues()
		.map(
			f =>
				`\t\t--${f.name})\n\t\t\tCOMPREPLY=( $(compgen -W "${f.values.join(' ')}" -- "$cur") )\n\t\t\treturn\n\t\t\t;;`,
		)
		.join('\n');
}

function bashChildCases(): string {
	return subcommandsWithChildren()
		.map(
			s =>
				`\t\t${s.name})\n\t\t\tCOMPREPLY=( $(compgen -W "${s.children.join(' ')}" -- "$cur") )\n\t\t\treturn\n\t\t\t;;`,
		)
		.join('\n');
}

export function renderBashCompletion(): string {
	const shorts = COMPLETION_FLAGS.filter(f => f.short).map(f => `-${f.short}`);
	const flags = [...longFlagNames(), ...shorts].join(' ');
	const subcommands = COMPLETION_SUBCOMMANDS.map(s => s.name).join(' ');
	return `# bash completion for nanocoder
# Generated by \`nanocoder completion bash\`. Source it from ~/.bashrc or drop
# it into a completion directory:
#   nanocoder completion bash >> ~/.bashrc

_nanocoder() {
	local cur prev
	cur="\${COMP_WORDS[COMP_CWORD]}"
	prev="\${COMP_WORDS[COMP_CWORD-1]}"

	local subcommands="${subcommands}"
	local flags="${flags}"

	case "$prev" in
${bashValueCases()}

${bashChildCases()}
	esac

	if [[ "$cur" == -* ]]; then
		COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
	else
		COMPREPLY=( $(compgen -W "$subcommands" -- "$cur") )
	fi
}

complete -F _nanocoder nanocoder
`;
}

function zshArgumentLine(flag: CompletionFlag): string {
	const long = `--${flag.name}`;
	const description = `[${zshEscape(flag.description)}]`;
	const pair = flag.short
		? `'(-${flag.short} ${long})'{-${flag.short},${long}}'`
		: null;
	if (flag.takesValue) {
		const valueSpec = flag.values
			? `:${flag.valueName ?? flag.name}:(${flag.values.join(' ')})`
			: `:${flag.valueName ?? flag.name}:`;
		return pair
			? `${pair}${description}${valueSpec}'`
			: `${long}='${description}${valueSpec}'`;
	}
	return pair ? `${pair}${description}'` : `'${long}${description}'`;
}

function zshChildrenCase(
	name: string,
	label: string,
	children: readonly string[],
): string {
	return `\t\t\t\t${name})\n\t\t\t\t\t_values '${label}' ${children.join(' ')}\n\t\t\t\t\t;;`;
}

export function renderZshCompletion(): string {
	const argumentLines = COMPLETION_FLAGS.map(
		f => `\t\t${zshArgumentLine(f)}`,
	).join(` \\\n`);
	const subcommandLines = COMPLETION_SUBCOMMANDS.map(
		s => `\t\t'${s.name}:${zshEscape(s.description)}'`,
	).join('\n');
	const childrenCases = subcommandsWithChildren()
		.map(s => zshChildrenCase(s.name, `${s.name} argument`, s.children))
		.join('\n');
	return `#compdef nanocoder
# zsh completion for nanocoder
# Generated by \`nanocoder completion zsh\`. Install it into your fpath:
#   mkdir -p ~/.oh-my-zsh/completions && nanocoder completion zsh > ~/.oh-my-zsh/completions/_nanocoder
# or eval it directly from ~/.zshrc:
#   eval "\$(nanocoder completion zsh)"

_nanocoder() {
	local line state

	local -a subcommands
	subcommands=(
${subcommandLines}
	)

	_arguments -C \\
${argumentLines} \\
		'1: :->subcommands' \\
		'*:: :->args'

	case $state in
		subcommands)
			_describe 'subcommand' subcommands
			;;
		args)
			case $line[1] in
${childrenCases}
			esac
			;;
	esac
}

if [ "\${funcstack[1]}" = "_nanocoder" ]; then
	_nanocoder "$@"
else
	compdef _nanocoder nanocoder
fi
`;
}

function fishFlagLine(flag: CompletionFlag): string {
	const names = flag.short
		? `-s ${flag.short} -l ${flag.name}`
		: `-l ${flag.name}`;
	const values = flag.values ? ` -a '${flag.values.join(' ')}'` : '';
	const requireParam = flag.takesValue ? ' -r' : '';
	return `\tcomplete -c nanocoder -f ${names}${requireParam}${values} -d '${fishEscape(flag.description)}'`;
}

function fishSubcommandLines(): string {
	return COMPLETION_SUBCOMMANDS.map(
		s =>
			`\tcomplete -c nanocoder -f -n '__fish_use_subcommand' -a '${s.name}' -d '${fishEscape(s.description)}'`,
	).join('\n');
}

function fishChildrenLines(): string {
	return subcommandsWithChildren()
		.map(
			s =>
				`\tcomplete -c nanocoder -f -n '__fish_seen_subcommand_from ${s.name}' -a '${s.children.join(' ')}'`,
		)
		.join('\n');
}

export function renderFishCompletion(): string {
	const flagLines = COMPLETION_FLAGS.map(f => fishFlagLine(f)).join('\n');
	return `# fish completion for nanocoder
# Generated by \`nanocoder completion fish\`. Install it with:
#   nanocoder completion fish > ~/.config/fish/completions/nanocoder.fish

complete -c nanocoder -f

# Subcommands
${fishSubcommandLines()}

# Subcommand arguments
${fishChildrenLines()}

# Flags
${flagLines}
`;
}
